version: '3.8'

networks:
  drs_network:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: drs_db
    networks:
      - drs_network
    environment:
      POSTGRES_DB: donation_registration_system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  gateway-api:
    build:
      context: .
      dockerfile: Gateway/Gateway.API/Dockerfile
    container_name: gateway_api
    networks:
      - drs_network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IntegrationSettings__AuthUri: "http://auth_api:8080/api/auth"
      IntegrationSettings__DonorUri: "http://donor_api:8080/api/donor"
      IntegrationSettings__DonationUri: "http://localhost:8080/api/donation"
      AuthSettings__SecretKey: "U7r4p$21xT!e8qLmZ9vFgH1rS6nK0wYc"
      AuthSettings__ExpirationMinutes: "30"
    ports:
      - "8080:8080"

  auth-api:
    build:
      context: .
      dockerfile: Auth/Auth.API/Dockerfile
    container_name: auth_api
    depends_on:
      - db
    networks:
      - drs_network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: "Host=drs_db;Port=5432;Pooling=true;Database=donation_registration_system;Username=admin;Password=admin"
      AuthSettings__SecretKey: "U7r4p$21xT!e8qLmZ9vFgH1rS6nK0wYc"
      AuthSettings__ExpirationMinutes: "30"

  donor-api:
    build:
      context: .
      dockerfile: Donor/Donor.API/Dockerfile
    container_name: donor_api
    depends_on:
      - db
    networks:
      - drs_network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: "Host=drs_db;Port=5432;Pooling=true;Database=donation_registration_system;Username=admin;Password=admin"

volumes:
  db-data: