// <auto-generated />
using System;
using Donation.Infrastructure.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Donation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116212504_Migrations")]
    partial class Migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Donation.Domain.Entities.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BagNumber")
                        .HasColumnType("text")
                        .HasColumnName("bag_number");

                    b.Property<DateTime>("DateOfDonation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_donation");

                    b.Property<int>("DonationType")
                        .HasColumnType("integer")
                        .HasColumnName("donation_type");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uuid")
                        .HasColumnName("donor_id");

                    b.Property<int>("VolumeMl")
                        .HasColumnType("integer")
                        .HasColumnName("volume_ml");

                    b.HasKey("Id");

                    b.ToTable("tb_donation");
                });
#pragma warning restore 612, 618
        }
    }
}
